apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/earpjennings37/say_when_git_ops.git
    chart: kube-prometheus-stack
    targetRevision: 58.2.2
    helm:
      valuesFiles:
        - values.yaml
        - monitoring.yaml
        - objstore.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
