# ============================
# GRAFANA (CHEAP MODE)
# ============================

# Access Grafana 2 ways:
# command line:kubectl port-forward svc/kube-prometheus-stack-grafana -n monitoring 3000:80 & then http://localhost:3000
# in k9: svc, shift-f, :secrets, x 
crds:
  enabled: true
grafana:
  enabled: true
  adminPassword: "admin"

  # No AWS LoadBalancer
  service:
    type: ClusterIP

  # Reduce resource usage
  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

# ============================
# PROMETHEUS (CHEAP MODE)
# ============================
prometheus:
  service:
    type: ClusterIP

  prometheusSpec:
    # Minimal retention to reduce EBS cost
    retention: 24h
    retentionSize: 1GB
    replicas: 1
    walCompression: true
    
    serviceAccountName: prometheus-kube-prometheus-prometheus

    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::026090519635:role/thanos-irsa-role

    thanos:
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore
          key: objstore.yml

    # Smallest safe storage volume
    storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: gp3
      accessModes:
        - ReadWriteOnce

      resources:
        requests:
          storage: 2Gi

    # Reduce CPU/memory footprint
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        memory: 400Mi


# ============================
# ALERTMANAGER (DISABLED)
# ============================
alertmanager:
  enabled: false

# ============================
# NODE EXPORTER (CHEAP MODE)
# ============================
nodeExporter:
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 50m
      memory: 50Mi

# ============================
# KUBE STATE METRICS (CHEAP MODE)
# ============================
kubeStateMetrics:
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi

# ============================
# PROMETHEUS OPERATOR (CHEAP MODE)
# ============================
prometheusOperator:
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi
  prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false