apiVersion: batch/v1
kind: CronJob
metadata:
  name: popeye
  namespace: popeye
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: popeye
          restartPolicy: Never

          containers:
            - name: popeye
              image: 026090519635.dkr.ecr.us-east-1.amazonaws.com/popeye-arm64:0.22.1-arm64
              imagePullPolicy: IfNotPresent

              command:
                - /bin/popeye

              args:
                - -o
                - yaml
                - --force-exit-zero

              resources:
                requests:
                  cpu: 25m
                  memory: 64Mi
                limits:
                  cpu: 100m
                  memory: 128Mi