apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  objstore.yml: |
    type: s3
    config:
      bucket: thanos-infinity-37
      endpoint: s3.amazonaws.com
      region: us-east-1
      insecure: false