apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: k8sgpt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://github.com/earpjennings37/say_when_git_ops.git
    targetRevision: main
    path: apps/k8sgpt

  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt-operator-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true