apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-bench
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/earpjennings37/say_when_git_ops.git
    targetRevision: main
    path: apps/kube-bench

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-bench

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true