apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-compactor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/earpjennings37/say_when_git_ops.git
    targetRevision: main
    path: apps/thanos-compactor
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: thanos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true