driver:
  enabled: true
  kind: modern_ebpf

  modernEbpf:
    leastPrivileged: true

tty: true

falco:
  json_output: true
  priority: warning

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

falcosidekick:
  enabled: true

  webui:
    enabled: true

    redis:
      storageEnabled: false