image:
  repository: quay.io/sustainable_computing_io/kepler
  tag: "v0.11.1"
  pullPolicy: IfNotPresent

securityContext:
  privileged: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: arm64

tolerations:
  - operator: Exists

service:
  type: ClusterIP

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s