# ============================
# TEMPO (CHEAP MODE)
# ============================
tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

  resources:
    requests:
      cpu: 20m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

  # Container security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL


# Pod security context
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001


service:
  type: ClusterIP


# Traces are currently ephemeral.
persistence:
  enabled: false