tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

service:
  type: ClusterIP

persistence:
  enabled: false

resources:
  requests:
    cpu: 20m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 200Mi