apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-store
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/earpjennings37/say_when_git_ops.git
    chart: thanos
    targetRevision: 12.3.0
    helm:
      valuesFiles:
        - values.yaml
        - thanos-store.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: thanos

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
