apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: thanos
      targetRevision: 12.7.0
      helm:
        valueFiles:
          - $values/apps/thanos/values.yaml

    - repoURL: https://github.com/earpjennings37/say_when_git_ops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true