# -----------------------------
# S3 Object Storage (IRSA)
# -----------------------------
objstoreConfig:
  type: s3
  config:
    bucket: thanos-infinity-37
    endpoint: s3.amazonaws.com
    region: us-east-1
    insecure: false

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::026090519635:role/thanos-irsa-role

# -----------------------------
# Thanos Query
# -----------------------------
query:
  enabled: true
  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# -----------------------------
# Thanos Store Gateway
# -----------------------------
storegateway:
  enabled: true
  replicaCount: 1

  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp3

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

# -----------------------------
# Thanos Compactor
# -----------------------------
compactor:
  enabled: true

  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp3

  retentionResolutionRaw: 7d
  retentionResolution5m: 30d
  retentionResolution1h: 90d

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# -----------------------------
# Disable non-essential components
# -----------------------------
bucketweb:
  enabled: false

queryFrontend:
  enabled: false

ruler:
  enabled: false

receive:
  enabled: false