server:
  service:
    type: ClusterIP
    servicePortHttp: 8080
    servicePortHttps: 8443
  ingress:
    enabled: false

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  enabled: true

redis:
  enabled: true

configs:
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance